Changed freenect2 from submodule to subproject with git.
LCAS/iai_kinect2 pull request #1
Opened 2018-07-20 13:15 UTC by MFernandezCarmona

Tested in docker container with catkin_make_isolated --build and seems to be working. Ready to try on the buildfarm

2018-07-20 13:52 UTC, marc-hanheide commented
You need to include`git` as `build_depend`

2018-07-20 13:53 UTC, marc-hanheide commented
And I think the install targets are still missing?

2018-07-20 13:54 UTC, marc-hanheide requested changes
Seemmy commemts

2018-07-20 14:25 UTC, MFernandezCarmona commented
I forgot about the install targets. Also added git as dependency.

2018-07-20 15:22 UTC, MFernandezCarmona commented
Refuses to install it...

"CMake Error at /opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake:323 (_install):
   install TARGETS given target "libfreenect2" which is not an executable,
   library, or module.
   Call Stack (most recent call first):
   CMakeLists.txt:51 (install)"

2018-07-22 17:16 UTC, marc-hanheide requested changes
I'm not quite sure why it wouldn't work but it is odd you commented this out.

2018-07-22 17:16 UTC, marc-hanheide commented on libfreenect2_ros/CMakeLists.txt
> +#  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
Why did you comment this out?

2018-07-23 08:25 UTC, MFernandezCarmona commented on libfreenect2_ros/CMakeLists.txt
> +#  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
At the beginning, because I thought that libfreenect2 only built a library called libfreenect2.so. But now I realize there  is also a testing program called "Protonect", so you're right.

2018-07-23 11:04 UTC, MFernandezCarmona commented
All this externalProject is driving me nuts. I will try to fork libfreenect2, create a ros package that builds the libraries from it and carry on from there.

2018-07-23 11:04 UTC, closed without merging